public class student_class {
    
    //Account a = new Account();
  //  Contact c = new Contact();a
   // Opportunity o = new Opportunity();
   // 
  //  public Account geta(){
  //      return a;
  //  }
  //   public Contact getc(){
  //      return c;
  //  }
   //  public Opportunity geto(){
    //    return o;
   // }
    
    public pageReference gotopage21(){
        return page.page21;
    }
    
     public pageReference gotopage22(){
        return page.page22;
    }
    
     public pageReference gotopage23(){
        return page.page23;
    }
     public pageReference gotopage24(){
        return page.page24;
    }
    
    public pageReference Save_now(){
       // insert a;
     //   c.AccountID = a.ID;
     //   insert c;
       // o.AccountID = a.ID;
       // insert o;
       // return page.page15;
       return null;
    }
}